resolvers:
    - 8.8.8.8
    - 208.67.222.222
    - 1.1.1.1
    - 9.9.9.9
    - 209.244.0.3
    - 64.6.64.6
    - 84.200.69.80
    - 8.26.56.26
    - 199.85.126.10
    - 81.218.119.11
    - 195.46.39.39
    - 23.94.60.240
    - 208.76.50.50
    - 216.146.35.35
    - 37.235.1.174
    - 198.101.242.72
    - 77.88.8.8
    - 91.239.100.100
    - 8.8.4.4
    - 208.67.220.220
    - 1.0.0.1
    - 149.112.112.112
    - 209.244.0.4
    - 64.6.65.6
    - 84.200.70.40
    - 8.20.247.20
    - 199.85.127.10
    - 209.88.198.133
    - 195.46.39.40
    - 128.52.130.209
    - 208.76.51.51
    - 216.146.36.36
    - 37.235.1.177
    - 23.253.163.53
    - 77.88.8.1
    - 89.233.43.71
sources:
    - alienvault
    - binaryedge
    - bufferover
    - certspotter
    - certspotterold
    - censys
    - chaos
    - crtsh
    - dnsdumpster
    - hackertarget
    - intelx
    - ipv4info
    - passivetotal
    - securitytrails
    - shodan
    - spyse
    - sublist3r
    - threatcrowd
    - threatminer
    - virustotal
all-sources:
    - alienvault
    - archiveis
    - binaryedge
    - bufferover
    - censys
    - certspotter
    - certspotterold
    - chaos
    - commoncrawl
    - crtsh
    - dnsdumpster
    - dnsdb
    - entrust
    - github
    - hackertarget
    - ipv4info
    - intelx
    - passivetotal
    - rapiddns
    - recon
    - securitytrails
    - shodan
    - sitedossier
    - spyse
    - sublist3r
    - threatcrowd
    - threatminer
    - virustotal
    - waybackarchive
    - zoomeye
recursive:
    - alienvault
    - bufferover
    - certspotter
    - certspotterold
    - crtsh
    - dnsdumpster
    - hackertarget
    - ipv4info
    - passivetotal
    - securitytrails
    - sublist3r
    - virustotal
binaryedge: []
censys: []
certspotter: []
chaos: []
dnsdb: []
github: []
intelx: []
passivetotal: []
securitytrails: []
shodan: []
spyse: []
urlscan: []
virustotal: []
zoomeye: []